# Generated by Django 5.0.6 on 2024-05-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='is_current_version',
            new_name='is_active',
        ),
    ]
