# Generated by Django 5.0.6 on 2024-05-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_is_current_version_version_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_version_name',
            field=models.CharField(default='No active version', max_length=50),
        ),
    ]
